<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KotohaIME.Core\KotohaIME.Core.csproj" />
    <InternalsVisibleTo Include="KotohaIME.App.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AstelioIME.ico" />
    <None Include="..\..\LICENSE" Link="LICENSE" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;ARM64;x64</Platforms>
    <RuntimeIdentifiers>win-arm64;win-x64</RuntimeIdentifiers>
    <AssemblyName>AstelioIME</AssemblyName>
    <Product>Astelio IME</Product>
    <Title>Astelio IME</Title>
    <Description>MS-IME向け入力カスタマイザー</Description>
    <Authors>Geek Fujiwara</Authors>
    <Company>Geek Fujiwara</Company>
    <Copyright>Copyright © 2026 Geek Fujiwara</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <ApplicationIcon>Assets\AstelioIME.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <Version>1.0.8</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

</Project>
